package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 31 DE MAYO DE 2019 12:42:24 COT
 */
public class PhIVR extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(14);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: Transferencia
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Transferencia", "Transferencia.wav", ""); 

		// phrase: Finalizar
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Finalizar", "Finalizar.wav", ""); 

		// phrase: BuenosDiasMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "BuenosDiasMenu", "BuenosDiasMenuPrincipal.wav", ""); 

		// phrase: BuenasTardesMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "BuenasTardesMenu", "BuenasTardesMenuPrincipal.wav", ""); 

		// phrase: BuenasNochesMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "BuenasNochesMenu", "BuenasNochesMenuPrincipal.wav", ""); 

		// phrase: MenuDos
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MenuDos", "MenuDos.wav", ""); 

		// phrase: OpcionValida
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "OpcionValida", "OpcionValida.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 14 DE JUNIO DE 2019 9:12:22 COT
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(PhIVR.PHRASE_MAP, phraseName));
	}
}
